### ISSUE TITLE
Error loading testup.rb in su2014/su2015

### ISSUE THREAD

**Issue by janbrouwer** [SketchUp/sketchup-developer-tools#51]
Testup fails to load in su2014/su2015 on windows 8.
Removing the semicolon at the end of the lines 37 and 45 in the file "sketchup-developer-tools/src/sketchup-developer-tools/testup/testup.rb" seems to fix the error.

**Comment by thomthom** [comment]
We have a new version of TestUp going forward from SU2014+:
https://github.com/SketchUp/testup-2

I'm been meaning to decouple this old TestUp from the developer tools project.
