### ISSUE TITLE
Get all Component Attribute values to save json format in database in ruby language 

### ISSUE THREAD

**Issue by SivaAdebeo** [SketchUp/sketchup-developer-tools#53]
![image](https://cloud.githubusercontent.com/assets/26133111/25034804/d332addc-2106-11e7-98bb-961c85929e07.png)

Hello,

I want to save the component attribute values to database through using json in ruby language. If anyone known about this please help me.

**Comment by thomthom** [comment]
Hi @SivaAdebeo .
I would recommend that you ask this question in the Developer section of the SketchUp forums: https://forums.sketchup.com/c/developers/ruby-api

I'm closing this issue as it's not related to this repository.
